### ISSUE TITLE
[Bug] Back to the list always go to "Accommodations"

### ISSUE THREAD

**Issue by unjello** [KoalicjaOtwartyKrakow/frontend#157]
"Back to the list" button in detailed view, always takes back to Accommodation List page.

## Expected result

Button takes back to respective List page - Hosts, Guests, Accommodations

**Comment by argasek** [comment]
@unjello Must have been broken with migration to the React Router v6. Assigning medium priority - it's irritating, but it's possible for the user to use workaround. Thanks for the report!

**Comment by argasek** [comment]
Closed in #178
