### ISSUE TITLE
[Common] [Tech] Gracefully handle HTTP 500 errors

### ISSUE THREAD

**Issue by argasek** [KoalicjaOtwartyKrakow/frontend#164]
In case of HTTP 500 errors, this loc in hooks:
```js
const parsed = JSON.parse(data);
```
throws an unhandled exception, as the data is not a JSON. Such scenario might happen under different conditions, so in general, a common `transformResponse` and `transformArrayResponse` functions are needed to handle such issues gracefully.

**Comment by mlazowik** [comment]
FYI as of ~now backend will send a proper json for 500 responses. However, this is only for exceptions we can catch, there might be other scenarios with responses outside of our control.
